apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: northwind-stack-deployment-cnab
  namespace: cnab
spec:
  replicas: 2
  template:
    metadata:
      labels:
        run: northwind-hybrid-cnab
    spec:
      containers:
        - image: northwindacr.azurecr.io/northwindclaimsnetcore:66
          name: northwindinsurance
          resources:
            requests:
              cpu: 200m
              memory: 1024Mi
          env:
           - name: LOCATION
             value: "AZURESTACK"
           - name: SQLCONNSTR_DefaultConnection
             value: "Data Source=sqldbk8s;Initial Catalog=northwindclaims;Integrated Security=False;User ID=sa;Password=User@123;Encrypt=False;ApplicationIntent=ReadWrite;MultiSubnetFailover=False"
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: cnab-regcred
