apiVersion: v1
kind: Service
metadata:
  # Name of the service
  name: northwind-service-cnab
  labels:
    run: northwind
spec:
  type: LoadBalancer
  ports:
    # the port that this service should serve on
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    # App name of the deployment it's trying to expose
    run: northwind-hybrid-cnab
