apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sql-deployment
  namespace: cnab
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: sqldbk8s
    spec:
      containers:
        - image: mcr.microsoft.com/mssql/server:2017-latest
          name: sqlserver
          resources:
            requests:
              cpu: 500m
              memory: 2048Mi
          env:
           - name: ACCEPT_EULA
             value: "Y"
           - name: SA_PASSWORD
             value: "User@123"
          ports:
            - containerPort: 1433