directories:
  output: release
  buildResources: resources
productName: porter-iot-remote-kube CNAB Bundle Installer
appId: com.microsoft.cnab.selfinstaller.porter-iot-remote-kube-cnab-self-installer
dmg:
  contents:
    - x: 410
      'y': 150
      type: link
      path: /Applications
    - x: 130
      'y': 150
      type: file
files:
  - filter:
      - dist/
      - img/
      - node_modules/
      - app.html
      - main.js
      - main.js.map
      - package.json
extraResources:
  - from: ./data
    to: data
mac:
  extraResources:
    - from: ./dufflebin/darwin-amd64/
      to: dufflebin/darwin
win:
  target: nsis
  extraResources:
    - from: ./dufflebin/windows-amd64/
      to: dufflebin/win32
linux:
  target:
    - deb
    - AppImage
  extraResources:
    - from: ./dufflebin/linux-amd64/
      to: dufflebin/linux
electronVersion: 1.8.8
